# Generated by Django 5.2.13 on 2026-04-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('Web Development', 'Web Development'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('AI & ML', 'AI & ML')], max_length=100)),
                ('batch', models.CharField(blank=True, choices=[('Batch A - Morning', 'Batch A - Morning'), ('Batch B - Evening', 'Batch B - Evening')], max_length=100, null=True)),
                ('total_fee', models.IntegerField(default=20000)),
                ('admission_status', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Confirmed', 'Confirmed'), ('Enrolled', 'Enrolled'), ('Dropped', 'Dropped')], default='Enquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], max_length=50)),
                ('payment_date', models.DateField()),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.student')),
            ],
        ),
    ]
