# Generated by Django 5.2.13 on 2026-04-21 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('Web Development', 'Web Development'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('AI & ML', 'AI & ML')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
