# Generated by Django 5.2.13 on 2026-05-04 09:50

import apps.admissions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_student_guardian_phone_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[apps.admissions.models.validate_reference]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.admissions.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.admissions.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
    ]
