# Generated by Django 5.2.13 on 2026-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_feepayment_created_at_student_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
